{
  "formatVersion": "1.1",
  "component": {
    "url": "../../chat/master/chat-master.module",
    "group": "io.github.elpafras",
    "module": "chat",
    "version": "master",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        }
      ],
      "files": [
        {
          "name": "chat.aar",
          "url": "chat-android-master.aar",
          "size": 26369,
          "sha512": "26b66aa813982cfd5833fc38b0060e81f8e5017690090d5a63254b5eb3b5742b3afec734a7c8ca6f23249aa026095feabcb8e6f05f683e1ae3cd80a44916d434",
          "sha256": "8d497cabfe18f057123f12f6d1573c878d25b8d731133d127e5110d23306e38b",
          "sha1": "9afc3687cc9b9c1a155a94567d857c2848387a06",
          "md5": "aff99b5ea304626a0633e5091b47da63"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "chat.aar",
          "url": "chat-android-master.aar",
          "size": 26369,
          "sha512": "26b66aa813982cfd5833fc38b0060e81f8e5017690090d5a63254b5eb3b5742b3afec734a7c8ca6f23249aa026095feabcb8e6f05f683e1ae3cd80a44916d434",
          "sha256": "8d497cabfe18f057123f12f6d1573c878d25b8d731133d127e5110d23306e38b",
          "sha1": "9afc3687cc9b9c1a155a94567d857c2848387a06",
          "md5": "aff99b5ea304626a0633e5091b47da63"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "chat-android-master-sources.jar",
          "url": "chat-android-master-sources.jar",
          "size": 6618,
          "sha512": "bad602a65e7cdb5b9a7b2986f61acbe3ef8ff109a0c4fd18d7bc6e84aa990418075a4d175e806b8a0d82a3c0bee821aeeb6c29e4b097ac046723070242329e2a",
          "sha256": "f9562a7dc9de325b502363fde45289df7d4b5841715fa36c687931818154af1d",
          "sha1": "95a990143fa608003868d32cf4a8c014c1402890",
          "md5": "f8a0865f118cd796a3b1810b97e2c6b5"
        }
      ]
    }
  ]
}
