{
  "formatVersion": "1.1",
  "component": {
    "url": "../../setting/2.0.0/setting-2.0.0.module",
    "group": "io.github.elpafras",
    "module": "setting",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "setting-iosArm64Main-2.0.0.klib",
          "url": "setting-iosarm64-2.0.0.klib",
          "size": 86324,
          "sha512": "68f7788d050ae5f8caf4c9daf00687d5aeff79c0e23d1fc8c51456da09890270e1da2d0f58b5d4c69de0290a2b63674702c208648dfab13b6151b39744ba0020",
          "sha256": "3350fbf4abaddd647952f54780c1bbf47534e501f3bf4faa3a49fe51aaeb9d1f",
          "sha1": "8a30f80c0931435331e46f7368548261bc6bfbfc",
          "md5": "5aca49b28041256d4ad7a486eb1bf8ee"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "setting-iosarm64-2.0.0-sources.jar",
          "url": "setting-iosarm64-2.0.0-sources.jar",
          "size": 23114,
          "sha512": "1dbfc17684cf4f98681f0876d9d3ab92255477538bdf1b8c3dc3b4c05e451cb8af3e39b56bdac3739a3f1fbc86f455fdbe1d632396132bd99385569598ee175a",
          "sha256": "a556ce6bb7e54ec927de75bf2c79948c9a92a631f7c0d10487a764bc5e2ea52d",
          "sha1": "56bdb819e508260fd441ed2e46f2e79ab18f0b89",
          "md5": "4a0eccc4742ca507c6726f7e29831029"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "setting-2.0.0.kotlin_resources.zip",
          "url": "setting-iosarm64-2.0.0-kotlin_resources.kotlin_resources.zip",
          "size": 340,
          "sha512": "1fbfd434d1a8935b8928bcf002177190259b28fcec9d44ab373261ae9fc6dbe38b069f79cbc0fa3749d1f78c9e4e9c1567595b321822ec80a2e581cc7d2f709c",
          "sha256": "a70624dede47b09380e2c9dbb8dd7088b2e1d2790de7f5e5235bca023830933c",
          "sha1": "93b8982f82e90bf83235de4efc69ff4fc4efda77",
          "md5": "3b5437f1e5a5208b140213f5a915655f"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "setting-iosarm64-2.0.0-metadata.jar",
          "url": "setting-iosarm64-2.0.0-metadata.jar",
          "size": 7095,
          "sha512": "7a81271a9ef4d97881cacca57a5312a2a6febdc06b7e9646da7bfecf07069b88b3ed1de704520530201bbe89b6829f7145c3ce374cf83ad9f753b399333210d8",
          "sha256": "30113f84408cb13a4926d247ae38e91ee35670aa8b24a8e6563ce06b00b06b7f",
          "sha1": "e907e08702746cc994a95e934f222ca67e7ea433",
          "md5": "d3629246f2f0e76e6bd86d8fe2e33308"
        }
      ]
    }
  ]
}
