{
  "formatVersion": "1.1",
  "component": {
    "url": "../../setting/2.0.0/setting-2.0.0.module",
    "group": "io.github.elpafras",
    "module": "setting",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "setting-iosSimulatorArm64Main-2.0.0.klib",
          "url": "setting-iossimulatorarm64-2.0.0.klib",
          "size": 86396,
          "sha512": "2fdddb2ca8b49f9352329dea71731dd01673bbbeb28dd30505859977d450e8429e07d5ae6bdccfb517227f7af1577fc00f45399721b8863db88bf418c8242ae0",
          "sha256": "c956210d6c9deda9e9f0872c39a299d625aa7bdf99be4acd115eb717f70d952b",
          "sha1": "51377eb235b62ae860e5f089981bf99bc7857d6b",
          "md5": "6426cb42bc878351f8c0a2f72ea662b1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "setting-iossimulatorarm64-2.0.0-sources.jar",
          "url": "setting-iossimulatorarm64-2.0.0-sources.jar",
          "size": 23258,
          "sha512": "1863407a260e143f03642d8788a2bf31dcf98506f54bec647f60bae7cc6f741c499e2d16ce052b6fc152ee83014c6a793a9b5db32f7a63eded5ff341c07ce38b",
          "sha256": "dd14ecdea54ec0370ec87bbc5fbbf2c0a9754368865f572adefc52f61c23a18c",
          "sha1": "f070a87c39667c372a541454c680eb9042665aba",
          "md5": "685518ad20c907c951d1bb300f3d3282"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "setting-2.0.0.kotlin_resources.zip",
          "url": "setting-iossimulatorarm64-2.0.0-kotlin_resources.kotlin_resources.zip",
          "size": 340,
          "sha512": "1fbfd434d1a8935b8928bcf002177190259b28fcec9d44ab373261ae9fc6dbe38b069f79cbc0fa3749d1f78c9e4e9c1567595b321822ec80a2e581cc7d2f709c",
          "sha256": "a70624dede47b09380e2c9dbb8dd7088b2e1d2790de7f5e5235bca023830933c",
          "sha1": "93b8982f82e90bf83235de4efc69ff4fc4efda77",
          "md5": "3b5437f1e5a5208b140213f5a915655f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "setting-iossimulatorarm64-2.0.0-metadata.jar",
          "url": "setting-iossimulatorarm64-2.0.0-metadata.jar",
          "size": 7095,
          "sha512": "7a81271a9ef4d97881cacca57a5312a2a6febdc06b7e9646da7bfecf07069b88b3ed1de704520530201bbe89b6829f7145c3ce374cf83ad9f753b399333210d8",
          "sha256": "30113f84408cb13a4926d247ae38e91ee35670aa8b24a8e6563ce06b00b06b7f",
          "sha1": "e907e08702746cc994a95e934f222ca67e7ea433",
          "md5": "d3629246f2f0e76e6bd86d8fe2e33308"
        }
      ]
    }
  ]
}
