{
  "formatVersion": "1.1",
  "component": {
    "url": "../../setting/2.0.0/setting-2.0.0.module",
    "group": "io.github.elpafras",
    "module": "setting",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "setting.aar",
          "url": "setting-android-2.0.0.aar",
          "size": 4237448,
          "sha512": "0ca8cf614c8217c611d99be62910e49ad26f28a95f4dd05580d411bb036e1e9302e4e69d45f29077fa22826601d927c1d94213c828c2b9063a3c177d75d7c89a",
          "sha256": "3c609714207c8292f977b3cb3ee18f2184f18e64372a378e0bdabe09231f33f2",
          "sha1": "f2d01188502e7c00ef7560fb1f6ba43733f32049",
          "md5": "ae8b75b016c5d3a32009943e52b5fa6d"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.14.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-resources",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.compose.components",
          "module": "components-ui-tooling-preview",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.8.2"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.18.0"
          }
        }
      ],
      "files": [
        {
          "name": "setting.aar",
          "url": "setting-android-2.0.0.aar",
          "size": 4237448,
          "sha512": "0ca8cf614c8217c611d99be62910e49ad26f28a95f4dd05580d411bb036e1e9302e4e69d45f29077fa22826601d927c1d94213c828c2b9063a3c177d75d7c89a",
          "sha256": "3c609714207c8292f977b3cb3ee18f2184f18e64372a378e0bdabe09231f33f2",
          "sha1": "f2d01188502e7c00ef7560fb1f6ba43733f32049",
          "md5": "ae8b75b016c5d3a32009943e52b5fa6d"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "setting-android-2.0.0-sources.jar",
          "url": "setting-android-2.0.0-sources.jar",
          "size": 30551,
          "sha512": "ed6d1e943bf5fc8ccb29b59e738dbdc6f41fac5dd9457d413ea76fe51aa59c055f05f8620eb7eeb61d64250d04a58648be3a43189060890a812b27ae210148be",
          "sha256": "59f3c7a485c10062b649172aa8f5208832511f393db276a3ac141a496909f06e",
          "sha1": "6e6a927fe909147b78bf44b7d8983297428d6138",
          "md5": "0e74627f525b6d1b02b16b96f2e9d064"
        }
      ]
    }
  ]
}
